# Generated by Django 4.1.5 on 2023-01-12 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0004_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('taskName', models.CharField(max_length=250)),
                ('taskDesc', models.CharField(max_length=250)),
                ('taskLocation', models.CharField(max_length=250)),
                ('taskStartDate', models.DateTimeField()),
                ('taskStopDate', models.DateTimeField()),
                ('taskPrice', models.IntegerField()),
                ('taskStatus', models.CharField(choices=[('Pending', 'Pending'), ('Started', 'Started'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('taskAssignedby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('taskCarriedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_carried_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
