# Generated by Django 4.1.5 on 2023-01-12 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0006_alter_tasks_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
