# Generated by Django 4.1.5 on 2023-01-13 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0007_rename_tasks_task_alter_task_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskCarriedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_carried_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
