# Generated by Django 4.1.5 on 2023-01-13 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0008_alter_task_taskcarriedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskAssignedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
