# Generated by Django 4.1.5 on 2023-01-15 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_backend', '0010_alter_task_taskprice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='task',
            table=None,
        ),
    ]
